# Generated by Django 6.0.4 on 2026-04-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptops', 'Laptops'), ('phones', 'Phones'), ('accessories', 'Accessories')], default='laptops', max_length=50),
        ),
    ]
